[versions]
java = "17"
fabric-loom = "1.5-SNAPSHOT"
minecraft = "1.20.4"
fabric-yarn = "1.20.4+build.3"
fabric-loader = "0.15.7"
fabric-api = "0.96.4+1.20.4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-yarn = { module = "net.fabricmc:yarn", version.ref = "fabric-yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
